version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: food-api
    container_name: food-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: food-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
