FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql

WORKDIR /var/www

COPY . .

RUN curl -sS https://getcomposer.org/installer | php
RUN php composer.phar install

EXPOSE 8000

CMD ["php-fpm"]
